#! /bin/sh
# /etc/init.d/shub
### BEGIN INIT INFO
# Provides:          sbus
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting shub"
    # run application you want to start
    exec forever start /home/pi/hub/index.js
    ;;
  stop)
    echo "Stopping shub"
    # kill application you want to stop
    exec forever stop /home/pi/hub/index.js
    ;;
  *)
    echo "Usage: /etc/init.d/shub {start|stop}"
    exit 1
    ;;
esac

exit 0